# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

os: Visual Studio 2015

environment:
  ARCH: "64"
  GENERATOR: Visual Studio 14 2015 Win64
  NUMPY: "1.14.5"
  PYTHON: "3.7"
  MSVC_DEFAULT_OPTIONS: ON
  ARROW_SRC: C:\apache-arrow
  PYARROW_VERSION: 0.12.1
  PYARROW_REF: ba09a9e93dc28da629f63e101e231c8b8df942d3

init:
  - set MINICONDA=C:\Miniconda35-x64
  - set PATH=%MINICONDA%;%MINICONDA%/Scripts;%MINICONDA%/Library/bin;%PATH%

build_script:
  - mkdir wheels
  - git clone -b zero-twelve-one-rc0 https://github.com/xhochy/arrow.git %ARROW_SRC% || exit /B
  - git -C %ARROW_SRC% checkout ba09a9e93dc28da629f63e101e231c8b8df942d3 || exit /B
  - call %ARROW_SRC%\dev\tasks\python-wheels\win-build.bat

after_build:
  xcopy %ARROW_SRC%\python\dist\* wheels\

artifacts:
  - path: wheels\*.whl

deploy:
  release: build-42-wheel-win-cp37m
  provider: GitHub
  auth_token: "%CROSSBOW_GITHUB_TOKEN%"
  artifact: /.*\.whl/
  draft: false
  prerelease: false

notifications:
  - provider: Email
    to:
      - uwelk@xhochy.com