# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

environment:
  ARROW_VERSION: 0.4.1.dev302
  # regardless of the python version we build against
  CONDA_INSTALL_LOCN: C:\Miniconda36-x64

# We always use a 64-bit machine, but can build x86 distributions
# with the TARGET_ARCH variable.
platform:
  - x64

install:
  # Cywing's git breaks conda-build. (See https://github.com/conda-forge/conda-smithy-feedstock/pull/2.)
  - cmd: rmdir C:\cygwin /s /q

  # Add path, activate `conda` and update conda.
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda.exe update --yes --quiet conda

  - cmd: set PYTHONUNBUFFERED=1

  # Configure the VM.
  - cmd: conda.exe install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build

# Skip .NET project specific build phase.
build: off

test_script:
  # Clone arrow
  - git clone -b ARROW-4893 https://github.com/xhochy/arrow.git arrow || exit /B
  - git -C arrow checkout bc445f857323f3f6d62a7c5e1b775319196ec849 || exit /B
  - pushd arrow\dev\tasks\conda-recipes

  # Configure conda
  - cmd: setup_conda_rc .\ .\ variants\win_c_compilervs2015cxx_compilervs2015python3.6.yaml
  - cmd: run_conda_forge_build_setup

  # Build the recipes
  - conda.exe build --output-folder . -m variants\win_c_compilervs2015cxx_compilervs2015python3.6.yaml parquet-cpp arrow-cpp pyarrow

  # Rename artifacts
  - pushd win-64
  - for %%f in (*.tar.bz2) do (
      set %%g=%%~nf
      ren "%%f" "%%~ng-win-64.tar.bz2"
    )

artifacts:
  # this must be relative and child of the build C:\projects\crossbow directory
  - path: arrow\dev\tasks\conda-recipes\win-64\*.tar.bz2

deploy:
  release: build-48-conda-win-vs2015-py36
  provider: GitHub
  auth_token: "%CROSSBOW_GITHUB_TOKEN%"
  artifact: /.*\.tar\.bz2/
  draft: false
  prerelease: false
  force_update: true

notifications:
  - provider: Email
    to:
      - Uwe.Korn@blue-yonder.com