jobs:
- job: linux
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 360

  variables:
    CONFIG: linux_python3.6
    ARROW_VERSION: 0.15.0.dev102
    DOCKER_IMAGE: condaforge/linux-anvil-comp7
    UPLOAD_PACKAGES: False

  steps:
  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    displayName: Configure binfmt_misc
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))

  - script: |
      git clone --no-checkout https://github.com/xhochy/arrow.git arrow
      git -C arrow fetch -t https://github.com/xhochy/arrow.git ARROW-6873
      git -C arrow checkout FETCH_HEAD
      git -C arrow submodule update --init --recursive
    displayName: Clone arrow

  - script: CI=azure ./run_docker_build.sh
    displayName: Run docker build
    workingDirectory: arrow/dev/tasks/conda-recipes

  # Using github release tries to find a common ancestor between the
  # currently pushed tag and the latest tag of the github repository
  # (don't know why).
  # The tag upload took 43 minutes because of this scan, so use an
  # alternative upload script.
  - task: CondaEnvironment@1
    inputs:
      packageSpecs: 'click github3.py jinja2 jira pygit2 ruamel.yaml setuptools_scm toolz'
      installOptions: '-c conda-forge'
      updateConda: false
  - script: |
      python arrow/dev/tasks/crossbow.py \
        --queue-path . \
        --queue-remote None \
        upload-artifacts \
        --sha build-53-azure-conda-linux-gcc-py36 \
        --tag build-53-azure-conda-linux-gcc-py36 \
        --pattern "arrow/dev/tasks/conda-recipes/build_artifacts/linux-64/*.tar.bz2"
    env:
      CROSSBOW_GITHUB_TOKEN: $(CROSSBOW_GITHUB_TOKEN)
    displayName: Upload packages as a GitHub release